### ISSUE TITLE
custom certificate 

### ISSUE THREAD

**Issue by emanuele-em** [emanuele-em/man-in-the-middle-proxy#5]
It might be a good idea to allow the user to select a cert to use instead of providing a CA that needs to be trusted by the system. This would allow users to take advantage of something like [mkcert](https://mkcert.dev/) for local use in a more flexible way.

**Comment by thermionic** [comment]
It **absolutely** needs to create its own root and not expect people to install an untrusted 3rd party root as trusted. The only exception would be to use a trusted (internal PKI) cert.

**Comment by emanuele-em** [comment]
Thank you very much, it isn't a difficult thing to implement but what is the concrete risk in this case?

**Comment by shirshak55** [comment]
@emanuele-em It is just about trust. When we install certificates from applications, we don't know if the certificate is signed via a strong private key that follows the best practice. When we install xyz application certs, we might give a chance to adversary to mitm our connection. 

That's why tools like HttpToolkit generally never install certificates and spawn browsers using the flag available in chrome or firefox. In fact, they also issue ephemeral certificates for the android app which is pretty cool.

**Comment by ebelliveau** [comment]
> It might be a good idea to allow the user to select a cert to use instead of providing a CA that needs to be trusted by the system. This would allow users to take advantage of something like [mkcert](https://mkcert.dev/) for local use in a more flexible way.

Thank you.  No way in hell I'm trusting someone's CA cert blindly.  Let me construct my own and include instructions to have it installed on target devices.

**Comment by emanuele-em** [comment]
is it a good idea open a menu on app startup and show to `upload` fields where to upload `.key` and `.cer`?

**Comment by shirshak55** [comment]
@emanuele-em 

Yes,

or you can just add to documentation that you can replace the .key and .cer file in /home/qu/........./mitm/cert.cert etc...

Shouldn't be that hard.

**Comment by emanuele-em** [comment]
ok, yes thank you very much
